# Generated by Django 4.2.27 on 2026-04-12 13:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partial"),
                        ],
                        default="started",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="started at"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "lab_client_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="laboratory client ID",
                    ),
                ),
                ("patients_created", models.IntegerField(default=0)),
                ("patients_updated", models.IntegerField(default=0)),
                ("doctors_created", models.IntegerField(default=0)),
                ("doctors_updated", models.IntegerField(default=0)),
                ("practices_created", models.IntegerField(default=0)),
                ("studies_created", models.IntegerField(default=0)),
                ("studies_updated", models.IntegerField(default=0)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("error_count", models.IntegerField(default=0)),
                ("last_synced_numero", models.BigIntegerField(blank=True, null=True)),
                ("last_synced_fecha", models.CharField(blank=True, max_length=8)),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "sync log",
                "verbose_name_plural": "sync logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncedRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_table",
                    models.CharField(
                        help_text="LabWin table name (e.g. PACIENTES, DETERS, MEDICOS)",
                        max_length=50,
                        verbose_name="source table",
                    ),
                ),
                (
                    "source_key",
                    models.CharField(
                        db_index=True,
                        help_text="LabWin primary key (e.g. NUMERO_FLD or composite key)",
                        max_length=100,
                        verbose_name="source key",
                    ),
                ),
                (
                    "target_model",
                    models.CharField(
                        help_text="LabControl model name (e.g. User, Study, Practice)",
                        max_length=50,
                        verbose_name="target model",
                    ),
                ),
                (
                    "target_uuid",
                    models.UUIDField(
                        db_index=True,
                        help_text="UUID of the created/updated LabControl object",
                        verbose_name="target UUID",
                    ),
                ),
                (
                    "lab_client_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="laboratory client ID",
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="synced at"),
                ),
                (
                    "sync_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="labwin_sync.synclog",
                        verbose_name="sync log",
                    ),
                ),
            ],
            options={
                "verbose_name": "synced record",
                "verbose_name_plural": "synced records",
                "indexes": [
                    models.Index(
                        fields=["source_table", "source_key"],
                        name="labwin_sync_source__09d906_idx",
                    )
                ],
                "unique_together": {("source_table", "source_key", "lab_client_id")},
            },
        ),
    ]
