# Generated by Django 4.2.27 on 2026-02-15 17:40

from django.db import migrations, models
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Determination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="code"),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Unit of measurement (e.g., mg/dL, g/L, cells/μL)",
                        max_length=50,
                        verbose_name="unit",
                    ),
                ),
                (
                    "reference_range",
                    models.CharField(
                        blank=True,
                        help_text="Normal reference range for this determination",
                        max_length=200,
                        verbose_name="reference range",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "determination",
                "verbose_name_plural": "determinations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalStudy",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Timestamp when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        verbose_name="UUID",
                    ),
                ),
                (
                    "lab_client_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="ID of the laboratory client this record belongs to",
                        null=True,
                        verbose_name="laboratory client ID",
                    ),
                ),
                (
                    "protocol_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique protocol identifier for this study",
                        max_length=50,
                        verbose_name="protocol number",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sample_collected", "Sample Collected"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "sample_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="sample ID"
                    ),
                ),
                (
                    "sample_collected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="sample collected at"
                    ),
                ),
                ("results", models.TextField(blank=True, verbose_name="results")),
                (
                    "results_file",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="results file",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes not visible to patient",
                        verbose_name="internal notes",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft delete flag - deleted studies are hidden but preserved",
                        verbose_name="is deleted",
                    ),
                ),
                ("history_user_id", models.UUIDField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical study",
                "verbose_name_plural": "historical studies",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Practice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "technique",
                    models.CharField(
                        blank=True,
                        help_text="Laboratory technique used for this practice",
                        max_length=200,
                        verbose_name="technique",
                    ),
                ),
                (
                    "sample_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of sample required (e.g., blood, urine, tissue)",
                        max_length=100,
                        verbose_name="sample type",
                    ),
                ),
                (
                    "sample_quantity",
                    models.CharField(
                        blank=True,
                        help_text="Required quantity of sample",
                        max_length=100,
                        verbose_name="sample quantity",
                    ),
                ),
                (
                    "sample_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Special instructions for sample collection",
                        verbose_name="sample instructions",
                    ),
                ),
                (
                    "conservation_transport",
                    models.TextField(
                        blank=True,
                        help_text="Instructions for sample conservation and transport",
                        verbose_name="conservation and transport",
                    ),
                ),
                (
                    "delay_days",
                    models.IntegerField(
                        default=0,
                        help_text="Expected delay in days for results",
                        verbose_name="delay (days)",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Price for this practice",
                        max_digits=10,
                        verbose_name="price",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "practice",
                "verbose_name_plural": "practices",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Study",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "lab_client_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="ID of the laboratory client this record belongs to",
                        null=True,
                        verbose_name="laboratory client ID",
                    ),
                ),
                (
                    "protocol_number",
                    models.CharField(
                        help_text="Unique protocol identifier for this study",
                        max_length=50,
                        unique=True,
                        verbose_name="protocol number",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sample_collected", "Sample Collected"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "sample_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="sample ID"
                    ),
                ),
                (
                    "sample_collected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="sample collected at"
                    ),
                ),
                ("results", models.TextField(blank=True, verbose_name="results")),
                (
                    "results_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="study_results/%Y/%m/",
                        verbose_name="results file",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes not visible to patient",
                        verbose_name="internal notes",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft delete flag - deleted studies are hidden but preserved",
                        verbose_name="is deleted",
                    ),
                ),
            ],
            options={
                "verbose_name": "study",
                "verbose_name_plural": "studies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserDetermination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="The measured value for this determination",
                        max_length=200,
                        verbose_name="value",
                    ),
                ),
                (
                    "is_abnormal",
                    models.BooleanField(
                        default=False,
                        help_text="Flag if value is outside normal range",
                        verbose_name="abnormal",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this result",
                        verbose_name="notes",
                    ),
                ),
            ],
            options={
                "verbose_name": "user determination",
                "verbose_name_plural": "user determinations",
                "ordering": ["study", "determination"],
            },
        ),
    ]
