# Generated by Django 4.2.27 on 2026-02-15 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetermination",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="userdetermination",
            name="determination",
            field=models.ForeignKey(
                help_text="The determination being measured",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_results",
                to="studies.determination",
            ),
        ),
        migrations.AddField(
            model_name="userdetermination",
            name="study",
            field=models.ForeignKey(
                help_text="The study this result belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="determination_results",
                to="studies.study",
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="ordered_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Doctor who ordered the study",
                limit_choices_to={"role": "doctor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ordered_studies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="patient",
            field=models.ForeignKey(
                limit_choices_to={"role": "patient"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="studies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="practice",
            field=models.ForeignKey(
                help_text="The practice/test being ordered",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="studies",
                to="studies.practice",
            ),
        ),
        migrations.AddField(
            model_name="practice",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="practice",
            name="determinations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Determinations/analytes included in this practice",
                related_name="practices",
                to="studies.determination",
                verbose_name="determinations",
            ),
        ),
        migrations.AddField(
            model_name="historicalstudy",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="historicalstudy",
            name="ordered_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Doctor who ordered the study",
                limit_choices_to={"role": "doctor"},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalstudy",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={"role": "patient"},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalstudy",
            name="practice",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The practice/test being ordered",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="studies.practice",
            ),
        ),
        migrations.AddField(
            model_name="determination",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userdetermination",
            unique_together={("study", "determination")},
        ),
        migrations.AddIndex(
            model_name="study",
            index=models.Index(
                fields=["protocol_number"], name="studies_stu_protoco_89d132_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="study",
            index=models.Index(
                fields=["patient", "status"], name="studies_stu_patient_8ac3f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="study",
            index=models.Index(
                fields=["lab_client_id"], name="studies_stu_lab_cli_f9b44b_idx"
            ),
        ),
    ]
