# Generated by Django 4.2.27 on 2026-01-24 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studytype",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="ordered_by",
            field=models.ForeignKey(
                help_text="Doctor or staff who ordered the study",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ordered_studies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="patient",
            field=models.ForeignKey(
                limit_choices_to={"role": "patient"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="studies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="study_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="studies",
                to="studies.studytype",
            ),
        ),
        migrations.AddField(
            model_name="historicalstudy",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="historicalstudy",
            name="ordered_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Doctor or staff who ordered the study",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalstudy",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={"role": "patient"},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalstudy",
            name="study_type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="studies.studytype",
            ),
        ),
        migrations.AddIndex(
            model_name="study",
            index=models.Index(
                fields=["order_number"], name="studies_stu_order_n_c84838_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="study",
            index=models.Index(
                fields=["patient", "status"], name="studies_stu_patient_8ac3f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="study",
            index=models.Index(
                fields=["lab_client_id"], name="studies_stu_lab_cli_f9b44b_idx"
            ),
        ),
    ]
