# Generated by Django 4.2.27 on 2026-01-31 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studies", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstudy",
            name="ordered_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Doctor who ordered the study",
                limit_choices_to={"role": "doctor"},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="ordered_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Doctor who ordered the study",
                limit_choices_to={"role": "doctor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ordered_studies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
