# Generated by Django 4.2.27 on 2026-02-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstudy",
            name="solicited_date",
            field=models.DateField(
                blank=True,
                help_text="Date the study was requested/ordered by the doctor",
                null=True,
                verbose_name="solicited date",
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="solicited_date",
            field=models.DateField(
                blank=True,
                help_text="Date the study was requested/ordered by the doctor",
                null=True,
                verbose_name="solicited date",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstudy",
            name="sample_collected_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time the physical sample was collected from the patient",
                null=True,
                verbose_name="sample collected at",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="sample_collected_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time the physical sample was collected from the patient",
                null=True,
                verbose_name="sample collected at",
            ),
        ),
    ]
