# Generated by Django 4.2.27 on 2026-04-25 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0003_add_practice_result_template_and_reference_range"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studypractice",
            unique_together=set(),
        ),
    ]
