# Generated by Django 4.2.27 on 2026-02-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0003_alter_historicalstudy_ordered_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studytype",
            name="practices",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of practices/tests included in this protocol with recommended values. Example: [{'name': 'Hemoglobin', 'unit': 'g/dL', 'min': 12.0, 'max': 16.0, 'description': 'Oxygen carrier'}]",
                verbose_name="practices",
            ),
        ),
    ]
