# Generated by Django 4.2.27 on 2026-02-01 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studies", "0004_studytype_practices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studytype",
            name="practices",
        ),
        migrations.CreateModel(
            name="Practice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "technique",
                    models.CharField(
                        blank=True,
                        help_text="Laboratory technique used for this practice",
                        max_length=200,
                        verbose_name="technique",
                    ),
                ),
                (
                    "sample_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of sample required (e.g., blood, urine, tissue)",
                        max_length=100,
                        verbose_name="sample type",
                    ),
                ),
                (
                    "sample_quantity",
                    models.CharField(
                        blank=True,
                        help_text="Required quantity of sample",
                        max_length=100,
                        verbose_name="sample quantity",
                    ),
                ),
                (
                    "sample_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Special instructions for sample collection",
                        verbose_name="sample instructions",
                    ),
                ),
                (
                    "conservation_transport",
                    models.TextField(
                        blank=True,
                        help_text="Instructions for sample conservation and transport",
                        verbose_name="conservation and transport",
                    ),
                ),
                (
                    "delay_days",
                    models.IntegerField(
                        default=0,
                        help_text="Expected delay in days for results",
                        verbose_name="delay (days)",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Price for this practice",
                        max_digits=10,
                        verbose_name="price",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "practice",
                "verbose_name_plural": "practices",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="studytype",
            name="practices",
            field=models.ManyToManyField(
                blank=True,
                help_text="Practices/tests included in this protocol",
                related_name="study_types",
                to="studies.practice",
                verbose_name="practices",
            ),
        ),
    ]
