# Generated by Django 4.2.27 on 2026-04-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0004_alter_studypractice_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstudy",
            name="is_paid",
            field=models.BooleanField(
                default=True,
                help_text="Whether the patient has settled the bono for this protocol. Sourced from LabWin PACIENTES.DEBEBONO_FLD: False only when DEBEBONO_FLD='1' (must pay bono); True otherwise (insurance, already paid, or N/A). Default True so manually-created studies and seed data are visible by default.",
                verbose_name="is paid",
            ),
        ),
        migrations.AddField(
            model_name="historicalstudy",
            name="is_validated",
            field=models.BooleanField(
                default=False,
                help_text="Whether all of this study's practices come from validated DETERS rows in LabWin (VALIDADO_FLD='1'). The sync only ingests validated DETERS today, so all sync-imported studies are is_validated=True. Manually-created studies start as False until lab staff validates them.",
                verbose_name="is validated",
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="is_paid",
            field=models.BooleanField(
                default=True,
                help_text="Whether the patient has settled the bono for this protocol. Sourced from LabWin PACIENTES.DEBEBONO_FLD: False only when DEBEBONO_FLD='1' (must pay bono); True otherwise (insurance, already paid, or N/A). Default True so manually-created studies and seed data are visible by default.",
                verbose_name="is paid",
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="is_validated",
            field=models.BooleanField(
                default=False,
                help_text="Whether all of this study's practices come from validated DETERS rows in LabWin (VALIDADO_FLD='1'). The sync only ingests validated DETERS today, so all sync-imported studies are is_validated=True. Manually-created studies start as False until lab staff validates them.",
                verbose_name="is validated",
            ),
        ),
    ]
