# Generated by Django 4.2.27 on 2026-04-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0004_rename_sample_collected_at_and_update_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstudy",
            name="completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when the results were delivered/completed",
                null=True,
                verbose_name="fecha de entrega",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstudy",
            name="service_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when the service was provided (sample collection date)",
                null=True,
                verbose_name="fecha de atención",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstudy",
            name="solicited_date",
            field=models.DateField(
                blank=True,
                help_text="Date the study was requested/ordered by the doctor",
                null=True,
                verbose_name="fecha de solicitud",
            ),
        ),
    ]
