# Generated by Django 4.2.27 on 2026-04-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "studies",
            "0005_historicalstudy_is_paid_historicalstudy_is_validated_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstudy",
            name="notification_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the 'study available' or 'password setup' email was sent to the patient. Null = patient has not been notified yet.",
                null=True,
                verbose_name="notification sent at",
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="notification_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the 'study available' or 'password setup' email was sent to the patient. Null = patient has not been notified yet.",
                null=True,
                verbose_name="notification sent at",
            ),
        ),
    ]
