# Generated by Django 4.2.27 on 2026-04-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0005_alter_historicalstudy_completed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="practice",
            name="code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Short code/abbreviation (e.g. LabWin ABREV_FLD)",
                max_length=20,
                verbose_name="code",
            ),
        ),
    ]
