# Generated by Django 4.2.27 on 2026-02-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0005_remove_studytype_practices_practice_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studytype",
            name="base_price",
        ),
    ]
