# Generated by Django 4.2.11 on 2025-11-29 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalInvoice",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Timestamp when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        verbose_name="UUID",
                    ),
                ),
                (
                    "lab_client_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="ID of the laboratory client this record belongs to",
                        null=True,
                        verbose_name="laboratory client ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="invoice number"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Payment"),
                            ("paid", "Paid"),
                            ("partially_paid", "Partially Paid"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="subtotal"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="tax amount",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="discount amount",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="total amount"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="paid amount",
                    ),
                ),
                ("issue_date", models.DateField(verbose_name="issue date")),
                ("due_date", models.DateField(verbose_name="due date")),
                (
                    "paid_date",
                    models.DateField(blank=True, null=True, verbose_name="paid date"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical invoice",
                "verbose_name_plural": "historical invoices",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPayment",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Timestamp when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        verbose_name="UUID",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="transaction ID"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="amount"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("bank_transfer", "Bank Transfer"),
                            ("online", "Online Payment"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="payment gateway"
                    ),
                ),
                (
                    "gateway_transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="gateway transaction ID",
                    ),
                ),
                (
                    "gateway_response",
                    models.JSONField(
                        blank=True, null=True, verbose_name="gateway response"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical payment",
                "verbose_name_plural": "historical payments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="invoice",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for this record",
                unique=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp when the record was last updated",
                verbose_name="updated at",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for this record",
                unique=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when the record was created",
                verbose_name="created at",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="lab_client_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="ID of the laboratory client this record belongs to",
                null=True,
                verbose_name="laboratory client ID",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp when the record was last updated",
                verbose_name="updated at",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when the record was created",
                verbose_name="created at",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["uuid"], name="payments_in_uuid_52300e_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["status", "due_date"], name="payments_in_status_68daea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["uuid"], name="payments_pa_uuid_cf872a_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "created_at"], name="payments_pa_status_343680_idx"
            ),
        ),
        migrations.AddField(
            model_name="historicalpayment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="historicalpayment",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalpayment",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="payments.invoice",
            ),
        ),
        migrations.AddField(
            model_name="historicalinvoice",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="historicalinvoice",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalinvoice",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={"role": "patient"},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalinvoice",
            name="study",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="studies.study",
            ),
        ),
    ]
