# Generated by Django 4.2.27 on 2026-04-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluser",
            name="dni",
            field=models.CharField(
                blank=True,
                help_text="Documento Nacional de Identidad",
                max_length=50,
                verbose_name="DNI",
            ),
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="phone number"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="dni",
            field=models.CharField(
                blank=True,
                help_text="Documento Nacional de Identidad",
                max_length=50,
                verbose_name="DNI",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="phone number"
            ),
        ),
    ]
