# Generated by Django 4.2.27 on 2026-01-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="language",
            field=models.CharField(
                choices=[("ES", "Spanish"), ("EN", "English")],
                default="ES",
                help_text="Preferred language for the user interface",
                max_length=2,
                verbose_name="preferred language",
            ),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="profile_picture",
            field=models.TextField(
                blank=True,
                help_text="User profile picture",
                max_length=100,
                null=True,
                verbose_name="profile picture",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("ES", "Spanish"), ("EN", "English")],
                default="ES",
                help_text="Preferred language for the user interface",
                max_length=2,
                verbose_name="preferred language",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="User profile picture",
                null=True,
                upload_to="profile_pictures/",
                verbose_name="profile picture",
            ),
        ),
    ]
