# Generated by Django 4.2.11 on 2025-12-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_historicaluser_user_created_by_user_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="verification_token",
            field=models.CharField(
                blank=True,
                help_text="Token for email verification",
                max_length=100,
                null=True,
                verbose_name="verification token",
            ),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="verification_token_created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="verification token created at"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_token",
            field=models.CharField(
                blank=True,
                help_text="Token for email verification",
                max_length=100,
                null=True,
                verbose_name="verification token",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_token_created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="verification token created at"
            ),
        ),
    ]
