# Generated by Django 4.2.27 on 2026-04-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_matricula_and_soft_delete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluser",
            name="email",
            field=models.EmailField(
                blank=True,
                db_index=True,
                help_text="Email address - required for patients, admin, and lab staff; optional for doctors",
                max_length=254,
                null=True,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Email address - required for patients, admin, and lab staff; optional for doctors",
                max_length=254,
                null=True,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
