# Generated by Django 4.2.27 on 2026-01-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_historicaluser_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="carnet",
            field=models.CharField(
                blank=True,
                help_text="Health insurance card number",
                max_length=50,
                verbose_name="carnet",
            ),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="direction",
            field=models.CharField(
                blank=True,
                help_text="User's street address",
                max_length=255,
                verbose_name="direction",
            ),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                help_text="User's gender",
                max_length=1,
                verbose_name="gender",
            ),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="User's city or location",
                max_length=200,
                verbose_name="location",
            ),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="mutual_code",
            field=models.IntegerField(
                blank=True,
                help_text="Health insurance mutual code",
                null=True,
                verbose_name="mutual code",
            ),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="mutual_name",
            field=models.CharField(
                blank=True,
                help_text="Health insurance mutual name",
                max_length=200,
                verbose_name="mutual name",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="carnet",
            field=models.CharField(
                blank=True,
                help_text="Health insurance card number",
                max_length=50,
                verbose_name="carnet",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="direction",
            field=models.CharField(
                blank=True,
                help_text="User's street address",
                max_length=255,
                verbose_name="direction",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                help_text="User's gender",
                max_length=1,
                verbose_name="gender",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="User's city or location",
                max_length=200,
                verbose_name="location",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="mutual_code",
            field=models.IntegerField(
                blank=True,
                help_text="Health insurance mutual code",
                null=True,
                verbose_name="mutual code",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="mutual_name",
            field=models.CharField(
                blank=True,
                help_text="Health insurance mutual name",
                max_length=200,
                verbose_name="mutual name",
            ),
        ),
    ]
