# Generated by Django 4.2.27 on 2026-02-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_historicaluser_carnet_historicaluser_direction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("lab_staff", "Laboratory Staff"),
                    ("doctor", "Doctor"),
                    ("patient", "Patient"),
                ],
                default="patient",
                max_length=20,
                verbose_name="user role",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("lab_staff", "Laboratory Staff"),
                    ("doctor", "Doctor"),
                    ("patient", "Patient"),
                ],
                default="patient",
                max_length=20,
                verbose_name="user role",
            ),
        ),
    ]
