# Generated by Django 4.2.27 on 2026-01-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_historicaluser_verification_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="birthday",
            field=models.DateField(
                blank=True,
                help_text="Date of birth",
                null=True,
                verbose_name="birthday",
            ),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="dni",
            field=models.CharField(
                blank=True,
                help_text="Documento Nacional de Identidad",
                max_length=20,
                verbose_name="DNI",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.DateField(
                blank=True,
                help_text="Date of birth",
                null=True,
                verbose_name="birthday",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="dni",
            field=models.CharField(
                blank=True,
                help_text="Documento Nacional de Identidad",
                max_length=20,
                verbose_name="DNI",
            ),
        ),
    ]
