# Generated by Django 4.2.27 on 2026-02-15 17:40

from django.db import migrations, models
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "lab_client_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="ID of the laboratory client this record belongs to",
                        null=True,
                        verbose_name="laboratory client ID",
                    ),
                ),
                (
                    "appointment_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="appointment number"
                    ),
                ),
                ("scheduled_date", models.DateField(verbose_name="scheduled date")),
                ("scheduled_time", models.TimeField(verbose_name="scheduled time")),
                (
                    "duration_minutes",
                    models.IntegerField(default=30, verbose_name="duration (minutes)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="confirmed at"
                    ),
                ),
                (
                    "checked_in_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="checked in at"
                    ),
                ),
                (
                    "checked_out_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="checked out at"
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, verbose_name="reason for visit"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="cancellation reason"),
                ),
                (
                    "reminder_sent",
                    models.BooleanField(default=False, verbose_name="reminder sent"),
                ),
                (
                    "reminder_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="reminder sent at"
                    ),
                ),
            ],
            options={
                "verbose_name": "appointment",
                "verbose_name_plural": "appointments",
                "ordering": ["scheduled_date", "scheduled_time"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalAppointment",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Timestamp when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        verbose_name="UUID",
                    ),
                ),
                (
                    "lab_client_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="ID of the laboratory client this record belongs to",
                        null=True,
                        verbose_name="laboratory client ID",
                    ),
                ),
                (
                    "appointment_number",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="appointment number"
                    ),
                ),
                ("scheduled_date", models.DateField(verbose_name="scheduled date")),
                ("scheduled_time", models.TimeField(verbose_name="scheduled time")),
                (
                    "duration_minutes",
                    models.IntegerField(default=30, verbose_name="duration (minutes)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="confirmed at"
                    ),
                ),
                (
                    "checked_in_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="checked in at"
                    ),
                ),
                (
                    "checked_out_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="checked out at"
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, verbose_name="reason for visit"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="cancellation reason"),
                ),
                (
                    "reminder_sent",
                    models.BooleanField(default=False, verbose_name="reminder sent"),
                ),
                (
                    "reminder_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="reminder sent at"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical appointment",
                "verbose_name_plural": "historical appointments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
