# Generated by Django 4.2.11 on 2025-11-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="appointment number"
                    ),
                ),
                ("scheduled_date", models.DateField(verbose_name="scheduled date")),
                ("scheduled_time", models.TimeField(verbose_name="scheduled time")),
                (
                    "duration_minutes",
                    models.IntegerField(default=30, verbose_name="duration (minutes)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="confirmed at"
                    ),
                ),
                (
                    "checked_in_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="checked in at"
                    ),
                ),
                (
                    "checked_out_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="checked out at"
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, verbose_name="reason for visit"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="cancellation reason"),
                ),
                (
                    "reminder_sent",
                    models.BooleanField(default=False, verbose_name="reminder sent"),
                ),
                (
                    "reminder_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="reminder sent at"
                    ),
                ),
                (
                    "lab_client_id",
                    models.IntegerField(null=True, verbose_name="laboratory client ID"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "appointment",
                "verbose_name_plural": "appointments",
                "ordering": ["scheduled_date", "scheduled_time"],
            },
        ),
    ]
